scenario: 'baseline'

scenario_inputs:
  baseline:
    zoning_table_name: 'zoning_baseline'
  test:
    zoning_table_name: 'zoning_test'

aggregation_tables:
- zones

store: sanfran_public.h5

building_sqft_per_job:
    -1: 400
    1: 400
    2: 400
    3: 400
    4: 355
    5: 1161
    6: 470
    7: 661
    8: 960
    9: 825
    10: 445
    11: 445
    12: 383
    13: 383
    14: 383

building_type_map:
    1: "Residential"
    2: "Residential"
    3: "Residential"
    4: "Office"
    5: "Hotel"
    6: "School"
    7: "Industrial"
    8: "Industrial"
    9: "Industrial"
    10: "Retail"
    11: "Retail"
    12: "Residential"
    13: "Retail"
    14: "Office"

form_to_btype:
    'residential':
      - 1
      - 2
      - 3
    'industrial':
      - 7
      - 8
      - 9
    'retail':
      - 10
      - 11
    'office':
      - 4
    'mixedresidential':
      - 12
    'mixedoffice':
      - 14

rates:
  households_relocation: .05
  jobs_relocation: .05
  simple_households_transition: .05
  simple_jobs_transition: .05


parcel_size_factor: 10.764

table_reprocess:
  jobs:
    fill_nas:
      job_category:
        how: "mode"
        type: "str"
  buildings:
    fill_nas:
      residential_sales_price:
        how: "zero"
        type: "float"
      non_residential_rent:
        how: "zero"
        type: "float"
      building_type_id:
        how: "mode"
        type: "int"
      residential_units:
        how: "zero"
        type: "int"
      non_residential_sqft:
        how: "zero"
        type: "int"
      year_built:
        how: "median"
        type: "int"


set_nan_price_to_zero: True

reconcile_residential_units_and_households: False

reconcile_non_residential_sqft_and_jobs: True