language: python
sudo: false
python:
- '2.7'
- '3.5'

install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- |
  conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy pandas pytest matplotlib scipy statsmodels
- source activate test-environment
- conda list
- pip install pycodestyle
- pip install https://github.com/UDST/orca/archive/master.zip
- pip install https://github.com/pksohn/urbansim/archive/python3.zip
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
     pip install pandana; else
     pip install https://github.com/UDST/osmnet/archive/python3-support.zip &&
     pip install https://github.com/UDST/pandana/archive/python3-support.zip; fi
- cd .. && git clone -b dev git@github.com:urbansim/developer.git
- pip install ./developer
- cd $TRAVIS_BUILD_DIR && pip install .

script:
- pycodestyle urbansim_parcels
- pycodestyle sf_example
- pycodestyle sd_example
- py.test
- cd $TRAVIS_BUILD_DIR/sf_example && python simulate.py
- cd $TRAVIS_BUILD_DIR/sd_example && python Simulation.py