language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install https://github.com/urbansim/developer/archive/master.zip
  - pip install .
  - pip install -r requirements-dev.txt
  - pip list

script:
  - pycodestyle urbansim_parcels
  - pycodestyle sd_example
  - pycodestyle sf_example
  - coverage run --source urbansim_parcels --module pytest --verbose
  - cd $TRAVIS_BUILD_DIR/sd_example
  - python simulate.py 
  - python simulate_occupancy.py
  - python simulate_pipeline.py
  - cd $TRAVIS_BUILD_DIR/sf_example
  - python simulate.py
  - python simulate_occupancy.py
  - python simulate_pipeline.py

after_success:
  - coverage report
