parcel_sizes:
- 10000.0

fars:
- 0.1
- 0.25
- 0.5
- 0.75
- 1.0
- 1.5
- 1.8
- 2.0
- 2.25
- 2.5
- 2.75
- 3.0
- 3.25
- 3.5
- 3.75
- 4.0
- 4.5
- 5.0
- 5.5
- 6.0
- 6.5
- 7.0
- 9.0
- 11.0

uses:
- retail
- industrial
- office
- residential

residential_uses:
- false
- false
- false
- true

forms:
    industrial:
        industrial: 1.0
    mixedoffice:
        office: 0.7
        residential: 0.3
    mixedresidential:
        residential: 0.9
        retail: 0.1
    office:
        office: 1.0
    residential:
        residential: 1.0
    retail:
        retail: 1.0

profit_factor: 1.1

building_efficiency: 0.7

parcel_coverage: 0.8

cap_rate: 0.05

parking_rates:
    industrial: 0.6
    office: 1.0
    residential: 1.0
    retail: 2.0

sqft_per_rate: 1000.0

parking_configs:
- surface
- deck
- underground

costs:
    industrial:
    - 140.0
    - 175.0
    - 200.0
    - 230.0
    office:
    - 160.0
    - 175.0
    - 200.0
    - 230.0
    residential:
    - 170.0
    - 190.0
    - 210.0
    - 240.0
    retail:
    - 160.0
    - 175.0
    - 200.0
    - 230.0

heights_for_costs:
- 15
- 55
- 120
- .inf

parking_sqft_d:
    deck: 250.0
    surface: 300.0
    underground: 250.0

parking_cost_d:
    deck: 90
    surface: 30
    underground: 110

height_per_story: 12.0

max_retail_height: 2.0

max_industrial_height: 2.0

only_built: true

parcel_filter: null

residential_to_yearly: true

forms_to_test:
- industrial
- mixedoffice
- mixedresidential
- office
- residential
- retail

pass_through: []

simple_zoning: false

construction_months:
    industrial:
    - 12.0
    - 14.0
    - 18.0
    - 24.0
    office:
    - 12.0
    - 14.0
    - 18.0
    - 24.0
    residential:
    - 12.0
    - 14.0
    - 18.0
    - 24.0
    retail:
    - 12.0
    - 14.0
    - 18.0
    - 24.0

construction_sqft_for_months:
- 10000
- 20000
- 50000
- .inf

loan_to_cost_ratio: 0.7

drawdown_factor: 0.6

interest_rate: 0.05

loan_fees: 0.02
